.TH HOSTINFO "8" "08 Feb 2018" "hostinfo" "Support Utilities Manual"
.SH NAME
hostinfo - Gathers basic host information for issue generator
.SH SYNOPSIS
hostinfo [OPTIONS]
.SH DESCRIPTION
Basic information about the host is gathered and displayed in a tag or label type format. 
.SH OPTIONS
.TP
\fB-h\fR
Show this help screen.
.TP
\fB-n\fR
Ignore network address output
.TP
\fB-m\fR
Ignore memory output
.TP
\fB-d\fR
Ignore disk checks and output
.TP
\fB-u\fR
Ignore update output
.TP
\fB-q\fR
Create the hostinfo file quietly
.TP
\fB-v\fR
Views the hostinfo file created by hostinfo, instead of updating the file
.SH AUTHOR
Jason Record <jason.record@suse.com>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
