.TH HOSTINFO "8" "12 Feb 2018" "hostinfo" "Support Utilities Manual"
.SH NAME
hostinfo - Gathers basic host information for issue generator
.SH SYNOPSIS
hostinfo [COMMAND]
.SH DESCRIPTION
Basic information about the host is gathered and displayed in a tag or label type format in the issue file. Relies on the issue-generator to create /etc/issue.
.SH COMMAND
.TP
\fBhelp\fR
The help screen
.TP
\fBall\fR
Run all commands (default)
.TP
\fBdist\fR
Gathers distribution information
.TP
\fBhost\fR
Gathers the server hostname
.TP
\fBkernel\fR
Gathers current kernel information
.TP
\fBupdates\fR
Gather current updates from zypper
.TP
\fBnetwork\fR
Update network information
.TP
\fBmemory\fR
Update memory information
.TP
\fBcpu\fR
Show current CPU load information
.TP
\fBdisk\fR
Show list is storage devices and their size
.RE
.SH FILES
.I /etc/hostinfo.conf
.RS
The hostinfo configuration file.
.RE
.SH AUTHOR
Jason Record <jason.record@suse.com>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
.SH SEE ALSO
.BR issue-generator (8)

