.TH hostinfo-updates "8" "12 Feb 2014" "hostinfo-updates" "Support Utilities Manual"
.SH NAME
hostinfo-updates - Gathers information that takes a little longer
.SH SYNOPSIS
hostinfo-updates [OPTIONS]
.SH DESCRIPTION
Gathers information about patches and makes it avialable to hostinfo. Runs as a daily cron by default.
.SH OPTIONS
.TP
\fB-v\fR
Show verbose output, otherwise run silently. This is the only valid option.
.SH AUTHOR
Jason Record <jrecord@suse.com>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
